site_name: Airflow-doc-zh
markdown_extensions:
    - toc:
        permalink: "#"
nav:
    - 'Introduction': 'index.md'
    - '贡献': '1.md'
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - python
